# Generated by Django 5.2.5 on 2025-08-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
