# Generated by Django 5.2.5 on 2025-08-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_category_name_alter_tag_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
