# Generated by Django 5.2.5 on 2025-09-03 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_post_users_liked"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
