# Generated by Django 5.2.5 on 2025-09-04 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_post_options_alter_category_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comments",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_comments",
                to="blog.post",
            ),
        ),
    ]
